// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcWsiGTB6HyZJMk8yHaX-Bs7Y4dTxlsMs',
    appId: '1:1095394074407:web:4317dea508ccd5c2fe1302',
    messagingSenderId: '1095394074407',
    projectId: 'movieszone-266e5',
    authDomain: 'movieszone-266e5.firebaseapp.com',
    databaseURL: 'https://movieszone-266e5.firebaseio.com',
    storageBucket: 'movieszone-266e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXHYLx9hRtZgK0AvbRfNSPgArbu7TH3lQ',
    appId: '1:1095394074407:android:20263cf79dc1a31bfe1302',
    messagingSenderId: '1095394074407',
    projectId: 'movieszone-266e5',
    databaseURL: 'https://movieszone-266e5.firebaseio.com',
    storageBucket: 'movieszone-266e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqisSukWz3L8z1zorE8nhT_Wgb-fDPKuQ',
    appId: '1:1095394074407:ios:f4c413cea786fc12fe1302',
    messagingSenderId: '1095394074407',
    projectId: 'movieszone-266e5',
    databaseURL: 'https://movieszone-266e5.firebaseio.com',
    storageBucket: 'movieszone-266e5.appspot.com',
    androidClientId: '1095394074407-6dg3p2t8o0rpvkcf9ui1sso93dcbtcoi.apps.googleusercontent.com',
    iosClientId: '1095394074407-2jm9p0838pqg68gsusac4m38uh3qos71.apps.googleusercontent.com',
    iosBundleId: 'com.example.leaderboard.leaderboard',
  );
}
